// git revert 要放弃的提交哈希值
export const localUserInfo = {
    "code": 1,
    "data": {
        "appMenuTreeBoList": [],
        "leaderDept": [],
        "mainDept": {
            "deptId": "1544239516923981826",
            "deptName": "组织",
            "id": "1808408701959147521",
            "mainFlag": 1,
            "orgId": "1",
            "orgName": "组织全称（河南众诚）",
            "orgTypeCode": null,
            "orgTypeName": null,
            "postId": null,
            "postName": null,
            "sortNum": "0.00",
            "userId": "1"
        },
        "menuTreeBoList": [
            {
                "id": "1782971139194662913",
                "pid": "0",
                "sortNum": 1,
                "label": "应用管理",
                "fullName": "应用管理",
                "parentId": "0",
                "enCode": "application",
                "path": "application",
                "frameFlag": null,
                "menuType": "M",
                "clientType": "0",
                "visibleFlag": "1",
                "perms": "",
                "icon": "component",
                "remark": null,
                "sysFlag": 1,
                "hasChildren": false,
                "children": [
                    {
                        "id": "1782971326642302978",
                        "pid": "1782971139194662913",
                        "sortNum": 2,
                        "label": "应用开发",
                        "fullName": "应用开发",
                        "parentId": "1782971139194662913",
                        "enCode": "develop",
                        "path": "develop",
                        "frameFlag": null,
                        "menuType": "C",
                        "clientType": "0",
                        "visibleFlag": "1",
                        "perms": "",
                        "icon": "",
                        "remark": null,
                        "sysFlag": 1,
                        "hasChildren": false,
                        "children": [
                            {
                                "id": "1782971523053170689",
                                "pid": "1782971326642302978",
                                "sortNum": 3,
                                "label": "新增应用",
                                "fullName": "新增应用",
                                "parentId": "1782971326642302978",
                                "enCode": "add",
                                "path": "",
                                "frameFlag": null,
                                "menuType": "A",
                                "clientType": "0",
                                "visibleFlag": "1",
                                "perms": "",
                                "icon": "",
                                "remark": null,
                                "sysFlag": 1,
                                "hasChildren": false,
                                "children": [],
                                "linkType": 0,
                                "linkUrl": null
                            }
                        ],
                        "linkType": 0,
                        "linkUrl": null
                    },
                    {
                        "id": "1782971675700670465",
                        "pid": "1782971139194662913",
                        "sortNum": 4,
                        "label": "应用授权",
                        "fullName": "应用授权",
                        "parentId": "1782971139194662913",
                        "enCode": "authoritySettings",
                        "path": "authoritySettings",
                        "frameFlag": null,
                        "menuType": "C",
                        "clientType": "0",
                        "visibleFlag": "1",
                        "perms": "",
                        "icon": "",
                        "remark": null,
                        "sysFlag": 1,
                        "hasChildren": false,
                        "children": [],
                        "linkType": 0,
                        "linkUrl": null
                    }
                ],
                "linkType": 0,
                "linkUrl": null
            },
            {
                "id": "1696711234347905026",
                "pid": "0",
                "sortNum": 2,
                "label": "消息配置",
                "fullName": "消息配置",
                "parentId": "0",
                "enCode": "xxpz",
                "path": "informationConfig",
                "frameFlag": null,
                "menuType": "C",
                "clientType": "0",
                "visibleFlag": "1",
                "perms": "",
                "icon": "select",
                "remark": null,
                "sysFlag": 1,
                "hasChildren": false,
                "children": [],
                "linkType": 0,
                "linkUrl": null
            },
            {
                "id": "1721352918608646145",
                "pid": "0",
                "sortNum": 3,
                "label": "插件中心",
                "fullName": "插件中心",
                "parentId": "0",
                "enCode": "cjzx",
                "path": "plugin",
                "frameFlag": null,
                "menuType": "M",
                "clientType": "0",
                "visibleFlag": "1",
                "perms": "",
                "icon": "code",
                "remark": null,
                "sysFlag": 1,
                "hasChildren": false,
                "children": [
                    {
                        "id": "1721353449909522434",
                        "pid": "1721352918608646145",
                        "sortNum": 2,
                        "label": "自定义三方",
                        "fullName": "自定义三方",
                        "parentId": "1721352918608646145",
                        "enCode": "zdysf",
                        "path": "custom",
                        "frameFlag": null,
                        "menuType": "C",
                        "clientType": "0",
                        "visibleFlag": "1",
                        "perms": "",
                        "icon": "",
                        "remark": null,
                        "sysFlag": 1,
                        "hasChildren": false,
                        "children": [],
                        "linkType": 0,
                        "linkUrl": null
                    },
                    {
                        "id": "1721354079818485761",
                        "pid": "1721352918608646145",
                        "sortNum": 5,
                        "label": "平台插件",
                        "fullName": "平台插件",
                        "parentId": "1721352918608646145",
                        "enCode": "ptcj",
                        "path": "platform",
                        "frameFlag": null,
                        "menuType": "C",
                        "clientType": "0",
                        "visibleFlag": "1",
                        "perms": "",
                        "icon": "",
                        "remark": null,
                        "sysFlag": 1,
                        "hasChildren": false,
                        "children": [],
                        "linkType": 0,
                        "linkUrl": null
                    }
                ],
                "linkType": 0,
                "linkUrl": null
            },
            {
                "id": "1744977750496235522",
                "pid": "0",
                "sortNum": 4,
                "label": "应用模板",
                "fullName": "应用模板",
                "parentId": "0",
                "enCode": "yymb",
                "path": "applib",
                "frameFlag": null,
                "menuType": "M",
                "clientType": "0",
                "visibleFlag": "1",
                "perms": "",
                "icon": "clipboard",
                "remark": null,
                "sysFlag": 1,
                "hasChildren": false,
                "children": [
                    {
                        "id": "1744978802025025538",
                        "pid": "1744977750496235522",
                        "sortNum": 99,
                        "label": "模板中心",
                        "fullName": "模板中心",
                        "parentId": "1744977750496235522",
                        "enCode": "mbzx",
                        "path": "center",
                        "frameFlag": null,
                        "menuType": "C",
                        "clientType": "0",
                        "visibleFlag": "1",
                        "perms": "",
                        "icon": "edit",
                        "remark": null,
                        "sysFlag": 1,
                        "hasChildren": false,
                        "children": [],
                        "linkType": 0,
                        "linkUrl": null
                    },
                    {
                        "id": "1744978643065098242",
                        "pid": "1744977750496235522",
                        "sortNum": 99,
                        "label": "我的应用",
                        "fullName": "我的应用",
                        "parentId": "1744977750496235522",
                        "enCode": "wdyy",
                        "path": "mine",
                        "frameFlag": null,
                        "menuType": "C",
                        "clientType": "0",
                        "visibleFlag": "1",
                        "perms": "",
                        "icon": "code",
                        "remark": null,
                        "sysFlag": 1,
                        "hasChildren": false,
                        "children": [],
                        "linkType": 0,
                        "linkUrl": null
                    }
                ],
                "linkType": 0,
                "linkUrl": null
            },
            {
                "id": "1",
                "pid": "0",
                "sortNum": 5,
                "label": "系统管理",
                "fullName": "系统管理",
                "parentId": "0",
                "enCode": "sys",
                "path": "system",
                "frameFlag": 1,
                "menuType": "M",
                "clientType": "0",
                "visibleFlag": "1",
                "perms": "system",
                "icon": "flow-back",
                "remark": "",
                "sysFlag": 1,
                "hasChildren": false,
                "children": [
                    {
                        "id": "1780414963810611202",
                        "pid": "1",
                        "sortNum": 0.1,
                        "label": "组织配置",
                        "fullName": "组织配置",
                        "parentId": "1",
                        "enCode": "zzpz",
                        "path": "orgConfig",
                        "frameFlag": null,
                        "menuType": "C",
                        "clientType": "0",
                        "visibleFlag": "1",
                        "perms": "",
                        "icon": "",
                        "remark": null,
                        "sysFlag": 1,
                        "hasChildren": false,
                        "children": [],
                        "linkType": 0,
                        "linkUrl": null
                    },
                    {
                        "id": "2",
                        "pid": "1",
                        "sortNum": 1,
                        "label": "租户管理",
                        "fullName": "租户管理",
                        "parentId": "1",
                        "enCode": "zhgl",
                        "path": "organization",
                        "frameFlag": 0,
                        "menuType": "C",
                        "clientType": "0",
                        "visibleFlag": "1",
                        "perms": null,
                        "icon": "",
                        "remark": "",
                        "sysFlag": 1,
                        "hasChildren": false,
                        "children": [],
                        "linkType": 0,
                        "linkUrl": null
                    },
                    {
                        "id": "1535078336255848450",
                        "pid": "1",
                        "sortNum": 2,
                        "label": "部门机构",
                        "fullName": "部门机构",
                        "parentId": "1",
                        "enCode": "bmjg",
                        "path": "department",
                        "frameFlag": 0,
                        "menuType": "C",
                        "clientType": "0",
                        "visibleFlag": "1",
                        "perms": null,
                        "icon": "",
                        "remark": "",
                        "sysFlag": 1,
                        "hasChildren": false,
                        "children": [],
                        "linkType": 0,
                        "linkUrl": null
                    },
                    {
                        "id": "4",
                        "pid": "1",
                        "sortNum": 3,
                        "label": "角色管理",
                        "fullName": "角色管理",
                        "parentId": "1",
                        "enCode": "role",
                        "path": "role",
                        "frameFlag": 0,
                        "menuType": "C",
                        "clientType": "0",
                        "visibleFlag": "1",
                        "perms": null,
                        "icon": "",
                        "remark": "",
                        "sysFlag": 1,
                        "hasChildren": false,
                        "children": [],
                        "linkType": 0,
                        "linkUrl": null
                    },
                    {
                        "id": "3",
                        "pid": "1",
                        "sortNum": 50,
                        "label": "岗位管理",
                        "fullName": "岗位管理",
                        "parentId": "1",
                        "enCode": "post",
                        "path": "postManagement",
                        "frameFlag": 0,
                        "menuType": "C",
                        "clientType": "0",
                        "visibleFlag": "1",
                        "perms": null,
                        "icon": "",
                        "remark": "",
                        "sysFlag": 1,
                        "hasChildren": false,
                        "children": [],
                        "linkType": 0,
                        "linkUrl": null
                    },
                    {
                        "id": "5",
                        "pid": "1",
                        "sortNum": 60,
                        "label": "用户管理",
                        "fullName": "用户管理",
                        "parentId": "1",
                        "enCode": "user",
                        "path": "user",
                        "frameFlag": 0,
                        "menuType": "C",
                        "clientType": "0",
                        "visibleFlag": "1",
                        "perms": null,
                        "icon": "",
                        "remark": "",
                        "sysFlag": 1,
                        "hasChildren": false,
                        "children": [],
                        "linkType": 0,
                        "linkUrl": null
                    },
                    {
                        "id": "8",
                        "pid": "1",
                        "sortNum": 80,
                        "label": "字典管理",
                        "fullName": "字典管理",
                        "parentId": "1",
                        "enCode": "dict",
                        "path": "dict",
                        "frameFlag": 0,
                        "menuType": "C",
                        "clientType": "0",
                        "visibleFlag": "1",
                        "perms": null,
                        "icon": "",
                        "remark": "",
                        "sysFlag": 1,
                        "hasChildren": false,
                        "children": [],
                        "linkType": 0,
                        "linkUrl": null
                    },
                    {
                        "id": "6",
                        "pid": "1",
                        "sortNum": 100,
                        "label": "菜单管理",
                        "fullName": "菜单管理",
                        "parentId": "1",
                        "enCode": "menu",
                        "path": "menu",
                        "frameFlag": 0,
                        "menuType": "C",
                        "clientType": "0",
                        "visibleFlag": "1",
                        "perms": null,
                        "icon": "",
                        "remark": "",
                        "sysFlag": 1,
                        "hasChildren": false,
                        "children": [],
                        "linkType": 0,
                        "linkUrl": null
                    },
                    {
                        "id": "1541973673699659778",
                        "pid": "1",
                        "sortNum": 999.99,
                        "label": "系统日志",
                        "fullName": "系统日志",
                        "parentId": "1",
                        "enCode": "log",
                        "path": "log",
                        "frameFlag": 0,
                        "menuType": "C",
                        "clientType": "0",
                        "visibleFlag": "1",
                        "perms": "log",
                        "icon": "404",
                        "remark": "",
                        "sysFlag": 1,
                        "hasChildren": false,
                        "children": [],
                        "linkType": 0,
                        "linkUrl": null
                    }
                ],
                "linkType": 0,
                "linkUrl": null
            },
            {
                "id": "2042077578103984130",
                "pid": "0",
                "sortNum": 99,
                "label": "库房管理",
                "fullName": "库房管理",
                "parentId": "0",
                "enCode": "kfgl",
                "path": "warehouse",
                "frameFlag": null,
                "menuType": "M",
                "clientType": "0",
                "visibleFlag": "1",
                "perms": "",
                "icon": "",
                "remark": null,
                "sysFlag": 0,
                "hasChildren": false,
                "children": [
                    {
                        "id": "2042077635876327426",
                        "pid": "2042077578103984130",
                        "sortNum": 10,
                        "label": "库房管理",
                        "fullName": "库房管理",
                        "parentId": "2042077578103984130",
                        "enCode": "kfgl",
                        "path": "warehouse",
                        "frameFlag": null,
                        "menuType": "C",
                        "clientType": "0",
                        "visibleFlag": "1",
                        "perms": "warehouse",
                        "icon": "",
                        "remark": null,
                        "sysFlag": 0,
                        "hasChildren": false,
                        "children": [],
                        "linkType": 0,
                        "linkUrl": ""
                    },
                    {
                        "id": "2042077777094348801",
                        "pid": "2042077578103984130",
                        "sortNum": 20,
                        "label": "平衡区管理",
                        "fullName": "平衡区管理",
                        "parentId": "2042077578103984130",
                        "enCode": "phqgl",
                        "path": "district",
                        "frameFlag": null,
                        "menuType": "C",
                        "clientType": "0",
                        "visibleFlag": "1",
                        "perms": "district",
                        "icon": "",
                        "remark": null,
                        "sysFlag": 0,
                        "hasChildren": false,
                        "children": [],
                        "linkType": 0,
                        "linkUrl": ""
                    },
                    {
                        "id": "2042077877820559361",
                        "pid": "2042077578103984130",
                        "sortNum": 99,
                        "label": "位置图管理",
                        "fullName": "位置图管理",
                        "parentId": "2042077578103984130",
                        "enCode": "wztgl",
                        "path": "locationDrawing",
                        "frameFlag": null,
                        "menuType": "C",
                        "clientType": "0",
                        "visibleFlag": "1",
                        "perms": "locationDrawing",
                        "icon": "",
                        "remark": null,
                        "sysFlag": 0,
                        "hasChildren": false,
                        "children": [],
                        "linkType": 0,
                        "linkUrl": ""
                    }
                ],
                "linkType": 0,
                "linkUrl": ""
            },
            {
                "id": "2042412186163056641",
                "pid": "0",
                "sortNum": 99,
                "label": "任务管理",
                "fullName": "任务管理",
                "parentId": "0",
                "enCode": "rwgl",
                "path": "task",
                "frameFlag": null,
                "menuType": "M",
                "clientType": "0",
                "visibleFlag": "1",
                "perms": "task",
                "icon": "",
                "remark": null,
                "sysFlag": 0,
                "hasChildren": false,
                "children": [
                    {
                        "id": "2042413215323623426",
                        "pid": "2042412186163056641",
                        "sortNum": 1,
                        "label": "入库管理",
                        "fullName": "入库管理",
                        "parentId": "2042412186163056641",
                        "enCode": "rkgl",
                        "path": "inbound",
                        "frameFlag": null,
                        "menuType": "C",
                        "clientType": "0",
                        "visibleFlag": "1",
                        "perms": "inbound",
                        "icon": "",
                        "remark": null,
                        "sysFlag": 0,
                        "hasChildren": false,
                        "children": [],
                        "linkType": 0,
                        "linkUrl": ""
                    },
                    {
                        "id": "2042413266322165762",
                        "pid": "2042412186163056641",
                        "sortNum": 2,
                        "label": "出库管理",
                        "fullName": "出库管理",
                        "parentId": "2042412186163056641",
                        "enCode": "ckgl",
                        "path": "outbound",
                        "frameFlag": null,
                        "menuType": "C",
                        "clientType": "0",
                        "visibleFlag": "1",
                        "perms": "outbound",
                        "icon": "",
                        "remark": null,
                        "sysFlag": 0,
                        "hasChildren": false,
                        "children": [],
                        "linkType": 0,
                        "linkUrl": ""
                    },
                    {
                        "id": "2042413345883918338",
                        "pid": "2042412186163056641",
                        "sortNum": 3,
                        "label": "位置移动",
                        "fullName": "位置移动",
                        "parentId": "2042412186163056641",
                        "enCode": "wzyd",
                        "path": "move",
                        "frameFlag": null,
                        "menuType": "C",
                        "clientType": "0",
                        "visibleFlag": "1",
                        "perms": "move",
                        "icon": "",
                        "remark": null,
                        "sysFlag": 0,
                        "hasChildren": false,
                        "children": [],
                        "linkType": 0,
                        "linkUrl": ""
                    },
                    {
                        "id": "2042413396815351809",
                        "pid": "2042412186163056641",
                        "sortNum": 4,
                        "label": "实物盘存",
                        "fullName": "实物盘存",
                        "parentId": "2042412186163056641",
                        "enCode": "swpc",
                        "path": "inventory",
                        "frameFlag": null,
                        "menuType": "C",
                        "clientType": "0",
                        "visibleFlag": "1",
                        "perms": "inventory",
                        "icon": "",
                        "remark": null,
                        "sysFlag": 0,
                        "hasChildren": false,
                        "children": [],
                        "linkType": 0,
                        "linkUrl": ""
                    }
                ],
                "linkType": 0,
                "linkUrl": ""
            },
            {
                "id": "3000000000000000000",
                "pid": "0",
                "sortNum": 100,
                "label": "数据管理",
                "fullName": "数据管理",
                "parentId": "0",
                "enCode": "dataManagement",
                "path": "dataManagement",
                "frameFlag": null,
                "menuType": "M",
                "clientType": "0",
                "visibleFlag": "1",
                "perms": "dataManagement",
                "icon": "",
                "remark": null,
                "sysFlag": 0,
                "hasChildren": false,
                "children": [
                    {
                        "id": "3000000000000000001",
                        "pid": "3000000000000000000",
                        "sortNum": 1,
                        "label": "初始录入",
                        "fullName": "初始录入",
                        "parentId": "3000000000000000000",
                        "enCode": "initialEntry",
                        "path": "initialEntry",
                        "frameFlag": null,
                        "menuType": "C",
                        "clientType": "0",
                        "visibleFlag": "1",
                        "perms": "initialEntry",
                        "icon": "",
                        "remark": null,
                        "sysFlag": 0,
                        "hasChildren": false,
                        "children": [],
                        "linkType": 0,
                        "linkUrl": ""
                    },
                    {
                        "id": "3000000000000000002",
                        "pid": "3000000000000000000",
                        "sortNum": 2,
                        "label": "变化量报表",
                        "fullName": "变化量报表",
                        "parentId": "3000000000000000000",
                        "enCode": "changeReport",
                        "path": "changeReport",
                        "frameFlag": null,
                        "menuType": "C",
                        "clientType": "0",
                        "visibleFlag": "1",
                        "perms": "changeReport",
                        "icon": "",
                        "remark": null,
                        "sysFlag": 0,
                        "hasChildren": false,
                        "children": [],
                        "linkType": 0,
                        "linkUrl": ""
                    },
                    {
                        "id": "3000000000000000003",
                        "pid": "3000000000000000000",
                        "sortNum": 3,
                        "label": "存量报表",
                        "fullName": "存量报表",
                        "parentId": "3000000000000000000",
                        "enCode": "inventoryReport",
                        "path": "inventoryReport",
                        "frameFlag": null,
                        "menuType": "C",
                        "clientType": "0",
                        "visibleFlag": "1",
                        "perms": "inventoryReport",
                        "icon": "",
                        "remark": null,
                        "sysFlag": 0,
                        "hasChildren": false,
                        "children": [],
                        "linkType": 0,
                        "linkUrl": ""
                    },
                    {
                        "id": "3000000000000000004",
                        "pid": "3000000000000000000",
                        "sortNum": 4,
                        "label": "封记台账",
                        "fullName": "封记台账",
                        "parentId": "3000000000000000000",
                        "enCode": "sealLedger",
                        "path": "sealLedger",
                        "frameFlag": null,
                        "menuType": "C",
                        "clientType": "0",
                        "visibleFlag": "1",
                        "perms": "sealLedger",
                        "icon": "",
                        "remark": null,
                        "sysFlag": 0,
                        "hasChildren": false,
                        "children": [],
                        "linkType": 0,
                        "linkUrl": ""
                    },
                    {
                        "id": "3000000000000000005",
                        "pid": "3000000000000000000",
                        "sortNum": 5,
                        "label": "材料管理",
                        "fullName": "材料管理",
                        "parentId": "3000000000000000000",
                        "enCode": "materialManagement",
                        "path": "materialManagement",
                        "frameFlag": null,
                        "menuType": "C",
                        "clientType": "0",
                        "visibleFlag": "1",
                        "perms": "materialManagement",
                        "icon": "",
                        "remark": null,
                        "sysFlag": 0,
                        "hasChildren": false,
                        "children": [],
                        "linkType": 0,
                        "linkUrl": ""
                    },
                    {
                        "id": "3000000000000000006",
                        "pid": "3000000000000000000",
                        "sortNum": 6,
                        "label": "标签模板管理",
                        "fullName": "标签模板管理",
                        "parentId": "3000000000000000000",
                        "enCode": "labelTemplate",
                        "path": "labelTemplate",
                        "frameFlag": null,
                        "menuType": "C",
                        "clientType": "0",
                        "visibleFlag": "1",
                        "perms": "labelTemplate",
                        "icon": "",
                        "remark": null,
                        "sysFlag": 0,
                        "hasChildren": false,
                        "children": [],
                        "linkType": 0,
                        "linkUrl": ""
                    },
                    {
                        "id": "3000000000000000007",
                        "pid": "3000000000000000000",
                        "sortNum": 7,
                        "label": "综合查询",
                        "fullName": "综合查询",
                        "parentId": "3000000000000000000",
                        "enCode": "comprehensiveQuery",
                        "path": "comprehensiveQuery",
                        "frameFlag": null,
                        "menuType": "C",
                        "clientType": "0",
                        "visibleFlag": "1",
                        "perms": "comprehensiveQuery",
                        "icon": "",
                        "remark": null,
                        "sysFlag": 0,
                        "hasChildren": false,
                        "children": [],
                        "linkType": 0,
                        "linkUrl": ""
                    },
                    {
                        "id": "3000000000000000008",
                        "pid": "3000000000000000000",
                        "sortNum": 8,
                        "label": "账目管理",
                        "fullName": "账目管理",
                        "parentId": "3000000000000000000",
                        "enCode": "accountManagement",
                        "path": "accountManagement",
                        "frameFlag": null,
                        "menuType": "C",
                        "clientType": "0",
                        "visibleFlag": "1",
                        "perms": "accountManagement",
                        "icon": "",
                        "remark": null,
                        "sysFlag": 0,
                        "hasChildren": false,
                        "children": [],
                        "linkType": 0,
                        "linkUrl": ""
                    }
                ],
                "linkType": 0,
                "linkUrl": ""
            }
        ],
        "otherDeptList": null,
        "roleList": [
            {
                "roleCode": "sys_manager",
                "roleId": "1455093401825787906",
                "roleName": "系统管理员",
                "userId": "1"
            }
        ],
        "tenantVO": {
            "childIds": [
                "1"
            ],
            "orgId": "1",
            "orgIds": [
                "1"
            ],
            "orgName": "组织全称（河南众诚）",
            "parentIds": [
                "1"
            ],
            "tenantId": "1"
        },
        "userBo": {
            "account": "admin",
            "basicId": "1",
            "birthday": "0",
            "certificatesNumber": null,
            "certificatesType": null,
            "dataSecretLevel": null,
            "description": "这是备注信息",
            "dingtalkPhone": "1",
            "education": null,
            "email": "1201111ddd222@qq.com",
            "entryDate": "0",
            "firstLoginIp": "127.0.0.1",
            "firstLoginTime": "1635295040000",
            "gender": 2,
            "headIcon": "/static/img/header-photo.png",
            "id": "1",
            "lastChangePasswordDate": "0",
            "lastLoginIp": "10.10.41.163",
            "lastLoginTime": "1776310118449",
            "loginAppFlag": 1,
            "loginServerFlag": 1,
            "managerUid": null,
            "mobilePhone": "13311112222",
            "nation": null,
            "nativePlace": null,
            "nickName": null,
            "postalAddress": null,
            "prevLoginIp": "10.10.41.163",
            "prevLoginTime": "1775786486754",
            "propertyJson": null,
            "quickQuery": null,
            "realName": "admin",
            "signature": null,
            "sortNum": "35.00",
            "sourceType": 1,
            "sysFlag": 0,
            "sysTheme": null,
            "telephone": "11111111111",
            "urgentContacts": null,
            "urgentTelephone": null,
            "workStatus": 2
        }
    },
    "msg": "操作成功",
    "success": true
}